Add actual code
Wojager/taskList pull request #2
Opened 2018-05-18 08:43 UTC by Wojager

2018-05-21 08:01 UTC, Mr-Eluzive requested changes

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/app.component.html
> +<app-todoList>Loading...</app-todoList>
Nazwy komponentów powinny być zapisywane kabab case'em.
`<app-todo-list>`

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/app.component.spec.ts
> +/* tslint:disable:no-unused-variable */
Testy z tego pliku są do wywalenia bo nie odnoszą się do obecnej wersji aplikacji.

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.css
> +    color:red;
Wcięcia powinny wynosić 2 spacje. Sprawdź wszędzie.

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.css
> +.deleteIcon {
kebab-case

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +
Niepotrzebne linijka

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +{{remain()}} out of {{todos.length}}
Dla czytelności:
```
{{ remain() }}
```
i
```
{{ todos.length }}
```
(dodanie spacji po {{ i przed }})

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +<h2>Lista zadań</h2>
Stosujemy w całości polski albo angielski, trzeba się zdecydować

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +dodaj zadanie <input type = "text" [(ngModel)] = 'newTodoTitle' (keyup.enter) = 'addTodo()'/>
W HTML bez spacji przed i po znaku `=`
W HTML zamiast `'` stosujemy `"`

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +<button type = 'submit' (click) = addTodo()>dodaj</button>
Nazwy metod w `"`

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +      <input [(ngModel)]="searchText" placeholder="search text goes here">
`searchText` nie został zdefiniowany w komponencie.

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +      <ul style = "list-style-type: none">
Styli nie wrzucaj w HTML tylko w pliku CSS

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +    <span [ngClass] = '{checked : todo.complete}'>{{todo.title}}, dodane o  {{todo.date | date: 'dd MMMM hh:mm:ss'}}</span>
Popraw wcięcia w tym pliku bo jest nieczytelnie.

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +</ul> -->
Usuń komentarz

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +
Dwie niepotrzebne puste linijki

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +  newTodoTitle: string = '';
Kiedy od razu przypisujesz wartość prymitywnego typu nie musisz podawać typu tej wartości. Jest wnioskowana automatycznie.

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +  todos: Array<Todo> = [];
```ts
Todo[]
```

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +    let il = 0;
Zakładam, że to jest skrót od "ilość". W kodzie utrzymujemy nazewnictwo angielskie także niech ta zmienna niech ma sensowną nazwę.

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +    this.todos.forEach(t => {
`forEach` nie jest tutaj raczej poprawne semantycznie. Ono jest bardziej po to, żeby wykonać coś na każdym elemencie. Tutaj lepiej byłoby `for ... of`

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +      }
Tutaj można zastosować skróconą składnię jeśli już.
```ts
i += t.complete ? i : 1;
```

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +  }
Ogólnie cała ta funkcja mogłaby wyglądać w ten sposób i byłaby schludniejsza:
```ts
remain() {
  const remainTasks = this.todos.filter(x => !x.complete);
  return remainTasks.length;
}
```

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +    if(!this.newTodoTitle){
Spacje:
```ts
if (!this.newTodoTitle) {
```
Taka forma, że przerywamy ma więcej sensu jeśli kod samej funkcji jest dłuższy niż w tym przypadku. Lepiej wrzucić do przeciwnego ifa kod całej funkcji.

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +    this.todos.splice(i, 1)
Brak średnika

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +    }
Puste linie po każdej metodzie

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +@Pipe({
Pipe nie może być w pliku komponentu 😱 .

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +
?? Bez takich odstępów.

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> +
??

2018-05-21 08:01 UTC, Mr-Eluzive commented on src/app/todoList/todoSearch.ts
> +
Do wywalenia...

2018-05-21 11:18 UTC, Mr-Eluzive requested changes
Ogólnie poza tymi zmianami pozostało Ci jeszcze zastosować kebab case dla nazw plików, klas CSS i ich ID.

2018-05-21 11:18 UTC, Mr-Eluzive commented on src/app/app.component.html
> +</h1>
Tutaj widzisz, że github zaznacza Ci tą linijkę w ten sposób bo na końcu każdego pliku powinna być jedna pusta linijka. Sprawdź wszędzie.

2018-05-21 11:18 UTC, Mr-Eluzive commented on src/app/todoList/pipeTodoList.ts
> +  }
Wcięcia. Przenieś gdzie indziej interfejs.

2018-05-21 11:18 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.html
> +  Tasks list</h2>
??

2018-05-21 11:18 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.spec.ts
> +      .compileComponents();
Niepotrzebna zmiana.

2018-05-21 11:18 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
>    complete: boolean;
Interfejs do oddzielnego pliku.

2018-05-24 07:38 UTC, Mr-Eluzive requested changes
Ogólnie przy robieniu poprawek dobrze by było stosować jednak tą praktykę o której mówiłem wcześniej. Jedna zmiana - jeden commit. Po zrobieniu wszystkich poprawek i wszystkich commitów, wrzucasz commity pod moimi komentarzami. Będzie lepiej wtedy widać co się czego tyczy i szybciej można będzie rozwiązać problemy.

2018-05-24 07:38 UTC, Mr-Eluzive commented on src/app/todoList/pipeTodoList.ts
>      }
```ts
transform(todos = [], searchText): Todo[] {
  if (todo && searchText) {
    return todos.filter(todo => todo.title.toLowerCase().includes(searchText.toLowerCase());
  }
  return todos;
}
```
Chyba wyglądałoby schludniej

2018-05-24 07:38 UTC, Mr-Eluzive commented on src/app/todoList/todoList.component.ts
> -
Dlaczego usunąłeś te linijki skoro w poprzednim commitcie przy review były one warunkiem?

2018-05-24 09:31 UTC, Wojager commented on src/app/todoList/pipeTodoList.ts
>      }
feb16da092fe67b3dde2435dad7aec9ea2f6b4e4

2018-05-24 09:32 UTC, Wojager commented on src/app/todoList/todoList.component.ts
> -
da1428880a85c3d05cab039f67e3e751e5dad42b

2018-05-25 10:56 UTC, Mr-Eluzive approved these changes

2018-05-29 11:47 UTC, merged